### ISSUE TITLE
LuckPerms And ViaBackwards Conflict

### ISSUE THREAD

**Issue by Skiller9090** [ViaVersion/ViaBackwards#204]
DUMP:
[04:40:27 INFO] [ViaBackwards]: Loading translations...
[04:40:27 INFO] [ViaBackwards]: Registering protocols...
[04:40:27 WARN]: Exception encountered when loading plugin: ViaBackwards
java.lang.NullPointerException: null
at us.myles.ViaVersion.api.protocol.ProtocolRegistry.addMappingLoaderFuture(ProtocolRegistry.java:365) ~[?:?]
at nl.matsv.viabackwards.api.BackwardsProtocol.executeAsyncAfterLoaded(BackwardsProtocol.java:47) ~[?:?]
at nl.matsv.viabackwards.protocol.protocol1_12_2to1_13.Protocol1_12_2To1_13.registerPackets(Protocol1_12_2To1_13.java:43) ~[?:?]
at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:29) ~[?:?]
at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:24) ~[?:?]
at nl.matsv.viabackwards.api.BackwardsProtocol.<init>(BackwardsProtocol.java:20) ~[?:?]
at nl.matsv.viabackwards.protocol.protocol1_12_2to1_13.Protocol1_12_2To1_13.<init>(Protocol1_12_2To1_13.java:37) ~[?:?]
at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:71) ~[?:?]
at nl.matsv.viabackwards.BungeePlugin.onEnable(BungeePlugin.java:20) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:285) ~[waterfall-341.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:288) ~[waterfall-341.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall-341.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-341.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e0795ab:341]
[04:40:27 INFO]: Enabled plugin cmd_list version git:cmd_list:1.15-SNAPSHOT:e0795ab:341 by WaterfallMC
[04:40:27 INFO]: Listening on /0.0.0.0:25565

### How/when does this error happen? login?:
This only happens when LuckPerms is present in the bungeecord server along side ViaBackwards causing viabackwards to fail loading.

**Comment by KennyTV** [comment]
`/viaver dump` output?

**Comment by Skiller9090** [comment]
https://dump.viaversion.com/d404147e2df181b1b03d79a113e08357df05d321c4703e155a9a69016f762c2a

**Comment by KennyTV** [comment]
And the full startup log please

**Comment by Skiller9090** [comment]
https://pastebin.com/4p4JWM7C

**Comment by Skiller9090** [comment]
So got any idea whats wrong, is it something i'm doing?

**Comment by KennyTV** [comment]
It's an issue on our side. For the time being, putting Via on your backend servers will fix it.

**Comment by Skiller9090** [comment]
Ok thank you

**Comment by chickenmcjesus** [comment]
Yep, experienced this same issue. Hope it gets resolved!
