### ISSUE TITLE
ConnectionOpenEvent to ViaVersion

### ISSUE THREAD

**Issue by Misick** [ViaVersion/ViaBackwards#210]
How/when does this error happen? login?:
> 10 sec. after startup 

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> [11:19:28 ERROR]: Could not pass event ConnectionOpenEvent to ViaVersion v3.0.0-SNAPSHOT
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener.onPacketReceiving(Lprotocolsupport/api/Connection$PacketListener$PacketEvent;)V @22: istore_3
  Reason:
    Type 'net/minecraft/server/v1_13_R2/EnumProtocol' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @22
    flags: { }
    locals: { 'us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener', 'protocolsupport/api/Connection$PacketListener$PacketEvent', 'net/minecraft/server/v1_13_R2/PacketHandshakingInSetProtocol' }
    stack: { 'net/minecraft/server/v1_13_R2/EnumProtocol' }
  Bytecode:
    0x0000000: 2bb6 001a c100 1c99 0034 2bb6 001a c000
    0x0000010: 1c4d 2cb6 0020 3e2a b400 11b6 0026 b200
    0x0000020: 2ca6 000a 1db2 0032 9f00 06a7 0010 2ab4
    0x0000030: 0011 b200 38b8 003c b600 422a b400 112a
    0x0000040: b600 46b1
  Stackmap Table:
    append_frame(@43,Object[#28],Integer)
    same_frame(@46)
    chop_frame(@59,2)

        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_241]
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_241]
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_241]
        at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_241]
        at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator$3.execute(ClassGenerator.java:240) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-e8d3881-c24abab]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at protocolsupport.protocol.pipeline.common.LogicHandler.channelActive(LogicHandler.java:81) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelActive(SimpleReadTimeoutHandler.java:27) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[11:19:29 ERROR]: Could not pass event ConnectionOpenEvent to ViaVersion v3.0.0-SNAPSHOT
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener.onPacketReceiving(Lprotocolsupport/api/Connection$PacketListener$PacketEvent;)V @22: istore_3
  Reason:
    Type 'net/minecraft/server/v1_13_R2/EnumProtocol' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @22
    flags: { }
    locals: { 'us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener', 'protocolsupport/api/Connection$PacketListener$PacketEvent', 'net/minecraft/server/v1_13_R2/PacketHandshakingInSetProtocol' }
    stack: { 'net/minecraft/server/v1_13_R2/EnumProtocol' }
  Bytecode:
    0x0000000: 2bb6 001a c100 1c99 0034 2bb6 001a c000
    0x0000010: 1c4d 2cb6 0020 3e2a b400 11b6 0026 b200
    0x0000020: 2ca6 000a 1db2 0032 9f00 06a7 0010 2ab4
    0x0000030: 0011 b200 38b8 003c b600 422a b400 112a
    0x0000040: b600 46b1
  Stackmap Table:
    append_frame(@43,Object[#28],Integer)
    same_frame(@46)
    chop_frame(@59,2)

        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_241]
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:1.8.0_241]
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_241]
        at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_241]
        at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator$3.execute(ClassGenerator.java:240) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-e8d3881-c24abab]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at protocolsupport.protocol.pipeline.common.LogicHandler.channelActive(LogicHandler.java:81) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelActive(SimpleReadTimeoutHandler.java:27) [ProtocolSupport.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot.jar:git-Spigot-e8d3881-c24abab]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by KennyTV** [comment]
You need Paper to run ViaVersion+ProtocolSupport.

**Comment by Misick** [comment]
oke ty
