### ISSUE TITLE
Unable to connect to 1.16.1 server with 1.15.2

### ISSUE THREAD

**Issue by Baterka** [ViaVersion/ViaBackwards#216]
**Describe the bug, provide any errors**
I am unable to connect to 1.16.1 server with 1.15.2 client. (https://github.com/ViaVersion/ViaVersion/issues/1863)
Stuck on: Loading terrain...

Seems like the problem is just when you switching from some server to 1.16 server (not tested different versions) with `/server` command, because it works fine when you join 1.16 server as default bungee server.

Works fine when ViaBackwards is on server (without proxy)

ViaVersion 3.0.2-SNAPSHOT

**How can we reproduce it?**

1. Login on 1.15.2 client
2. Join Bungee proxy server
3. Join 1.15 server
4. Use command `/server<servername>` to switch to 1.16 server
5. Stuck on "Loading terrain..." screen forever
6. No error in console

**Expected behaviour**
Should work same way as 1.8-1,15 client on 1.15 server.

**Screenshots**
![image](https://user-images.githubusercontent.com/3463591/86107848-b0bfc100-bac2-11ea-8f59-12514e94fcd6.png)

**Dump**
https://dump.viaversion.com/f3ed140580297909d124a3d5946a341f417b7c975302ccd5d461836714d9ca4e
(Ignore blocked protocols. I blocked them after I realized this bug.)

**Additional server info**
Waterfall #358

**Comment by KennyTV** [comment]
Please don't discard issue templates - we need your dump and info on additional sofware/proxy.

**Comment by Baterka** [comment]
updated

**Comment by KennyTV** [comment]
Try these 2 things separately: Moving Via to your backend servers, and trying without other plugins on a testserver please

**Comment by Baterka** [comment]
> Try these 2 things separately: Moving Via to your backend servers, and trying without other plugins on a testserver please

Seems like problem only on Linux. Working fine on Win 10 with same server files.

**Comment by Baterka** [comment]
@KennyTV When I am trying to directly connect to this server trough bungee (default server) I am getting this error:
```
[12:11:38] [Netty Worker IO Thread #5/INFO]: [CZBaterka|/217.195.174.242:46925] <-> ServerConnector [survival] has connected
[12:11:39] [Netty Worker IO Thread #5/WARN] [ViaVersion]: ERROR IN Protocol1_15_2To1_16 IN REMAP OF DECLARE_RECIPES (0x5A)
[12:11:39] [Netty Worker IO Thread #5/ERROR]: [/217.195.174.242:46925|CZBaterka] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:183) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:143) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:113) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at nl.matsv.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16.lambda$new$0(BlockItemPackets1_16.java:43) ~[?:?]
	at nl.matsv.viabackwards.api.rewriters.ItemRewriter.handleItemToClient(ItemRewriter.java:70) ~[?:?]
	at nl.matsv.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16.handleItemToClient(BlockItemPackets1_16.java:298) ~[?:?]
	at nl.matsv.viabackwards.protocol.protocol1_13_2to1_14.data.RecipeRewriter1_14.handleCraftingShaped(RecipeRewriter1_14.java:48) ~[?:?]
	at nl.matsv.viabackwards.protocol.protocol1_15_2to1_16.data.RecipeRewriter1_16.handle(RecipeRewriter1_16.java:56) ~[?:?]
	at nl.matsv.viabackwards.protocol.protocol1_15_2to1_16.data.RecipeRewriter1_16$1.lambda$registerMap$0(RecipeRewriter1_16.java:40) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:127) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:419) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304) ~[?:?]
	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:34) ~[?:?]
	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:14) ~[?:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	... 43 more
[12:11:39] [Netty Worker IO Thread #5/INFO]: [CZBaterka] disconnected with: EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToMessageEncoder:104
[12:11:39] [Netty Worker IO Thread #5/INFO]: [/217.195.174.242:46925|CZBaterka] -> UpstreamBridge has disconnected
```

**Comment by Baterka** [comment]
@KennyTV Ok so I found the problem I think... This behaviour hapenning only when you moving from 1.15.2 server to 1.16.1 server by `/server <servername>`

**Comment by KennyTV** [comment]
> Try these 2 things separately: Moving Via to your backend servers, and trying without other plugins on a testserver please
Did you try these? The info above doesn't help too much 👀

**Comment by Baterka** [comment]
Yes. Both working fine. Only one setup does not work:
**Servers:**
1. Bungee server with Via
2. Paper server on 1.15.2 (Default for bungee)
3. Paper server on 1.16.1

BUngee connects you to 1.15 default server. You want to move to 1.16 server by `/server <servername>`. You got stuck on Loading terrain...

**Comment by KennyTV** [comment]
Is that with Bungee or Waterfall? (can you try both?)

**Comment by KennyTV** [comment]
I was able to reproduce it, my guess it that Bungee doesn't send a second respawn anymore since it thinks the client is on 1.16. I'll see if I can fix it

**Comment by Baterka** [comment]
> Is that with Bungee or Waterfall? (can you try both?)

yes

**Comment by KennyTV** [comment]
You also have to update ViaVersion to https://ci.viaversion.com/job/ViaVersion/427/
