### ISSUE TITLE
NoSuchMethod when start on bungeecord

### ISSUE THREAD

**Issue by orblazer** [ViaVersion/ViaBackwards#233]
**Describe the bug, provide any errors**
When start server i have that error :
```
java.lang.NoSuchMethodError: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.ChatRewriter.legacyTextToJson(Ljava/lang/String;)Ljava/lang/String;
        at nl.matsv.viabackwards.api.entities.storage.EntityData.jsonName(EntityData.java:28) ~[?:?]
        at nl.matsv.viabackwards.protocol.protocol1_13_2to1_14.packets.EntityPackets1_14.registerRewrites(EntityPackets1_14.java:332) ~[?:?]
        at nl.matsv.viabackwards.api.rewriters.Rewriter.register(Rewriter.java:27) ~[?:?]
        at nl.matsv.viabackwards.protocol.protocol1_13_2to1_14.Protocol1_13_2To1_14.registerPackets(Protocol1_13_2To1_14.java:51) ~[?:?]
        at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:69) ~[?:?]
        at nl.matsv.viabackwards.api.BackwardsProtocol.<init>(BackwardsProtocol.java:22) ~[?:?]
        at nl.matsv.viabackwards.protocol.protocol1_13_2to1_14.Protocol1_13_2To1_14.<init>(Protocol1_13_2To1_14.java:32) ~[?:?]
        at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:79) ~[?:?]
        at nl.matsv.viabackwards.BungeePlugin.lambda$onLoad$0(BungeePlugin.java:21) ~[?:?]
        at us.myles.ViaVersion.ViaManager.init(ViaManager.java:75) ~[?:?]
        at us.myles.ViaVersion.BungeePlugin.onEnable(BungeePlugin.java:75) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[Waterfall-365.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:3c6c0a2:365]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[Waterfall-365.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:3c6c0a2:365]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[Waterfall-365.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:3c6c0a2:365]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall-365.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:3c6c0a2:365]
```

**How can we reproduce it?**
1. Install ViaVersion and ViaBackwards 3.0.1
2. Start server with last version of Bungeecord

**Expected behaviour**
Start server without errror

**Comment by KennyTV** [comment]
Please follow the issue template (and make sure the ViaVersion matches the ViaBackwards version, -Dev goes with -Dev)
