### ISSUE TITLE
NPE on Velocity

### ISSUE THREAD

**Issue by MeFisto94** [ViaVersion/ViaBackwards#235]
**Describe the bug, provide any errors**
```
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java:186) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:171) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:121) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:191) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:153) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
at nl.matsv.viabackwards.protocol.protocol1_14_4to1_15.packets.BlockItemPackets1_15.lambda$new$0(BlockItemPackets1_15.java:28) ~[?:?]
at nl.matsv.viabackwards.api.rewriters.ItemRewriter.handleItemToClient(ItemRewriter.java:70) ~[?:?]
at nl.matsv.viabackwards.protocol.protocol1_14_4to1_15.data.RecipeRewriter1_15.handleStonecutting(RecipeRewriter1_15.java:40) ~[?:?]
at nl.matsv.viabackwards.protocol.protocol1_14_4to1_15.data.RecipeRewriter1_15.handle(RecipeRewriter1_15.java:31) ~[?:?]
at nl.matsv.viabackwards.api.rewriters.RecipeRewriter$1.lambda$registerMap$0(RecipeRewriter.java:27) ~[?:?]
at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19) ~[?:?]
at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:127) ~[?:?]
at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:419) ~[?:?]
at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:432) ~[?:?]
at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81) ~[?:?]
at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:323) ~[?:?]
at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:301) ~[?:?]
at us.myles.ViaVersion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:38) ~[?:?]
at us.myles.ViaVersion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:17) ~[?:?]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[velocity.jar:1.0.9-SNAPSHOT (git-e038a71b-b229)]
... 45 more
```

**How can we reproduce it?**
Join a velocity powered server.
Since I only saw that in the console I am uncertain about any specifics, but it happens when attempting to join, it seems.

Edit: I can reproduce this as well when joining with an 1.8 client

**Expected behaviour**
The exception shouldn't be thrown

**ViaVersion Dump:**
https://dump.viaversion.com/79de1353c8d125b2d0cc112b1938a979887eb2087c06f4a8b64d5c237ef04e7a

**Additional server info**
See the dump, this happens on Velocity, we didn't have issues with Bungee.

**Comment by KennyTV** [comment]
Update ViaVersion and ViaBackwards to the -Dev builds on https://ci.viaversion.com/
