### ISSUE TITLE
I get this error with the new viaversion. 

### ISSUE THREAD

**Issue by Porkason** [ViaVersion/ViaBackwards#281]
[ERROR] Error occurred while enabling ViaBackwards v3.1.1 (Is it up to date?)

java.lang.NoSuchMethodError: us.myles.ViaVersion.api.protocol.Protocol.<init>(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Z)V

at nl.matsv.viabackwards.api.BackwardsProtocol.<init>(BackwardsProtocol.java:21) ~[?:?]

at nl.matsv.viabackwards.protocol.protocol1_9_4to1_10.Protocol1_9_4To1_10.<init>(Protocol1_9_4To1_10.java:31) ~[?:?]

at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:68) ~[?:?]

at nl.matsv.viabackwards.BukkitPlugin.onEnable(BukkitPlugin.java:25) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]

at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]

at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]

at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:184) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]

at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]

at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-57bbdd8-dea4138]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by KennyTV** [comment]
https://github.com/ViaVersion/ViaBackwards/releases/tag/3.2.0

**Comment by Porkason** [comment]
i get the issue with viabackwards. is there no new version?

**Comment by DoctorMacc** [comment]
Kenny linked you the new version.
