### ISSUE TITLE
Error enabling ViaBackwards after ViaVersion update

### ISSUE THREAD

**Issue by RalphORama** [ViaVersion/ViaBackwards#285]
## Describe the bug, provide any errors

```log
[17:28:58 INFO]: [ViaBackwards] Enabling ViaBackwards v3.1.1
[17:28:58 INFO]: [ViaBackwards] Loading translations...
[17:28:58 INFO]: [ViaBackwards] Registering protocols...
[17:28:58 ERROR]: Error occurred while enabling ViaBackwards v3.1.1 (Is it up to date?)
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.protocol.Protocol.<init>(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Z)V
        at nl.matsv.viabackwards.api.BackwardsProtocol.<init>(BackwardsProtocol.java:21) ~[?:?]
        at nl.matsv.viabackwards.protocol.protocol1_9_4to1_10.Protocol1_9_4To1_10.<init>(Protocol1_9_4To1_10.java:31) ~[?:?]
        at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:68) ~[?:?]
        at nl.matsv.viabackwards.BukkitPlugin.onEnable(BukkitPlugin.java:25) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:205) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
[17:28:58 INFO]: [ViaBackwards] Disabling ViaBackwards v3.1.1
```

Got this error starting my server after updating Via**Version** to 3.2.0

## How can we reproduce it?

1. Set up paperMC server
2. Install latest ViaBackwards file from SpigotMC
3. Install latest ViaVersion file from SpigotMC
4. Error occurs when starting the server

## Expected behaviour

No error when enabling the plugin

## ViaVersion Dump:

- https://dump.viaversion.com/b7f8e58ffe0ef35221209339d5cb928d7dc0d0a33761043abef5e065e58d852e

## Additional server info

- Server software is `git-Paper-253 (MC: 1.16.3)`

## Checklist

- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Blocksnmore** [comment]
You don't have the latest viabackwards. Download it from ci. Links:
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.1-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.2.0.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.3-SNAPSHOT.jar
