### ISSUE TITLE
Deleted chunk

### ISSUE THREAD

**Issue by smaks6** [ViaVersion/ViaBackwards#305]
I have a problem because every time I turn on the server an error pops up and then when I enter the server, 1 random chunk is removed. How can this be fixed?
Server version: 1.16.4
Plugin version: latest
Error:
[10:15:50] [Paper RegionFile IO Thread/WARN]: Region file ./world/region/r.0.0.mca has an invalid sector at index: 160; size has to be > 0[10:15:50] [Paper RegionFile IO Thread/ERROR]: Detected invalid header for regionfile /root/pvp/./world/region/r.0.0.mca! Recalculating header...[10:15:50] [Paper RegionFile IO Thread/ERROR]: Recalculating regionfile /root/pvp/./world/region/r.0.0.mca, header gave erroneous offsets & locations[10:15:50] [Paper RegionFile IO Thread/WARN]: Corrupt regionfile header detected! Attempting to re-calculate header offsets for regionfile /root/pvp/./world/region/r.0.0.mcajava.lang.Throwable: nullat net.minecraft.server.v1_16_R3.RegionFile.recalculateHeader(RegionFile.java:121) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at net.minecraft.server.v1_16_R3.RegionFile.<init>(RegionFile.java:523) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at net.minecraft.server.v1_16_R3.RegionFile.<init>(RegionFile.java:408) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at net.minecraft.server.v1_16_R3.RegionFileCache.getFile(RegionFileCache.java:90) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at net.minecraft.server.v1_16_R3.RegionFileCache.read(RegionFileCache.java:174) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at net.minecraft.server.v1_16_R3.IChunkLoader.read(IChunkLoader.java:104) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at net.minecraft.server.v1_16_R3.PlayerChunkMap.read(PlayerChunkMap.java:1720) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at net.minecraft.server.v1_16_R3.WorldServer$2.readData(WorldServer.java:156) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at com.destroystokyo.paper.io.PaperFileIOThread$ChunkDataTask.run(PaperFileIOThread.java:508) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]

**Comment by KennyTV** [comment]
Not a Via issue, probably just Yatopia being Yatopia.

**Comment by smaks6** [comment]
and can you add compatibility with this engine?

**Comment by KennyTV** [comment]
What? That's just Yatopia corrupting chunks, nothing to do with Via, and nothing Via can do about it. 👀
