### ISSUE TITLE
Doesn't work on 1.12.2 paper

### ISSUE THREAD

**Issue by SladeHazard** [ViaVersion/ViaBackwards#362]
### '/viaversion dump' Output

https://dump.viaversion.com/51e065469bf03404954c19f9c8c9996ce30982a39967ba9285161faeb031d02a

### Console Error

[03:17:00 INFO]: [ViaBackwards] Enabling ViaBackwards v4.0.0-1.17-pre4-SNAPSHOT
[03:17:00 INFO]: [ViaBackwards] Loading translations...
[03:17:00 INFO]: [ViaBackwards] Registering protocols...
[03:17:00 INFO]: [ViaBackwards] Loading 1.10 -> 1.9.4 mappings...
[03:17:00 INFO]: [ViaBackwards] Loading 1.11 -> 1.10 mappings...
[03:17:00 ERROR]: Error occurred while enabling ViaBackwards v4.0.0-1.17-pre4-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.addMappingLoaderFuture(ProtocolManagerImpl.java:427) ~[?:?]
        at com.viaversion.viabackwards.api.BackwardsProtocol.executeAsyncAfterLoaded(BackwardsProtocol.java:45) ~[?:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.Protocol1_12_2To1_13.registerPackets(Protocol1_12_2To1_13.java:57) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.<init>(AbstractProtocol.java:68) ~[?:?]
        at com.viaversion.viabackwards.api.BackwardsProtocol.<init>(BackwardsProtocol.java:38) ~[?:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.Protocol1_12_2To1_13.<init>(Protocol1_12_2To1_13.java:52) ~[?:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:87) ~[?:?]
        at com.viaversion.viabackwards.BukkitPlugin.onEnable(BukkitPlugin.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[server.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[server.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[server.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[server.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) ~[server.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[server.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

### Bug Description

doesnt work

### Steps to Reproduce

load plg on 1.12.2

### Expected Behavior

work

### Additional Server Info

1.12.2
paper

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Can't reproduce. Do you have late-bind enabled/disabled? And please send the full startup logs.

**Comment by SladeHazard** [comment]
Enabled,
https://pastebin.com/5HCxLHmA
