### ISSUE TITLE
Viabackwards Crash

### ISSUE THREAD

**Issue by KeyAs99** [ViaVersion/ViaBackwards#372]
### '/viaversion dump' Output

https://dump.viaversion.com/00a30cb178bead9e99b35d59f528e6cb9b6dec121adcf80cc211347374f07b2b

### Console Error

[02:55:09] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] METADATA_LIST initializing ViaBackwards v4.0.1-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: METADATA_LIST
	at com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.packets.EntityPackets1_16.registerPackets(EntityPackets1_16.java:180) ~[?:?]
	at com.viaversion.viaversion.api.rewriter.RewriterBase.register(RewriterBase.java:36) ~[?:?]
	at com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.Protocol1_15_2To1_16.registerPackets(Protocol1_15_2To1_16.java:78) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:76) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:173) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:167) ~[?:?]
	at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:100) ~[?:?]
	at com.viaversion.viabackwards.BukkitPlugin.init(BukkitPlugin.java:48) ~[?:?]
	at com.viaversion.viabackwards.BukkitPlugin.onLoad(BukkitPlugin.java:36) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-771]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-771]
	at java.lang.Thread.run(Thread.java:829) [?:?]

### Bug Description

I can't join my server with 1.16-1.16.4 due to that error.

### Steps to Reproduce

1. Add viabackwards and viaversion in 1.16.5 paper server
2. Block these protocols [5,47,107,108,109,110,210,315,316,335,338,340,393,401,404,477,480,485,490,498,573,575,578]
3. Join with client 1.16

### Expected Behavior

I have viaversion and viabackwards. My server is 1.16.5 and viaversion works good but viabackwards not.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
You're outdated.
