### ISSUE TITLE
Kick Tresaure map

### ISSUE THREAD

**Issue by franxyk** [ViaVersion/ViaBackwards#382]
### '/viaversion dump' Output

https://dump.viaversion.com/3e247369aad4f5768c37165408cfc4e5e64de518547be3f334ec49e6da93a5e8

### Console Error

```
[12:38:03] [Netty Epoll Server IO #3/WARN]: [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF MAP_DATA (0x27)
[12:38:03] [Netty Epoll Server IO #3/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:38:03] [Netty Epoll Server IO #3/WARN]: {Type: JsonElement, Data: [Pair{Type|VarInt, 659}, Pair{Type|Byte, 0}, Pair{Type|Boolean, true}, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|VarInt, 1}, Pair{Type|Byte, 118}, Pair{Type|Byte, 96}, Pair{Type|Byte, 1}, Pair{Type|Boolean, true}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$10 (Anonymous), Packet ID: 37}
[12:38:03] [Netty Epoll Server IO #3/WARN]: Actual Error: 
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:38:03] [Netty Epoll Server IO #3/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:38:03] [Netty Epoll Server IO #3/WARN]: {Type: JsonElement, Data: [Pair{Type|VarInt, 659}, Pair{Type|Byte, 0}, Pair{Type|Boolean, true}, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|VarInt, 1}, Pair{Type|Byte, 118}, Pair{Type|Byte, 96}, Pair{Type|Byte, 1}, Pair{Type|Boolean, true}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$10 (Anonymous), Packet ID: 37}
[12:38:03] [Netty Epoll Server IO #3/WARN]: Actual Error: 
[12:38:03] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 256)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:40)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:48)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:41)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:32)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:171)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viabackwards.api.rewriters.MapColorRewriter.lambda$getRewriteHandler$0(MapColorRewriter.java:41)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:289)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:268)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:38:03] [Netty Epoll Server IO #3/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:38:03] [Netty Epoll Server IO #3/WARN]: {Type: JsonElement, Data: [Pair{Type|VarInt, 659}, Pair{Type|Byte, 0}, Pair{Type|Boolean, true}, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|VarInt, 1}, Pair{Type|Byte, 118}, Pair{Type|Byte, 96}, Pair{Type|Byte, 1}, Pair{Type|Boolean, true}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$10 (Anonymous), Packet ID: 37}
[12:38:03] [Netty Epoll Server IO #3/WARN]: Actual Error: 
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:38:03] [Netty Epoll Server IO #3/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:38:03] [Netty Epoll Server IO #3/WARN]: {Type: JsonElement, Data: [Pair{Type|VarInt, 659}, Pair{Type|Byte, 0}, Pair{Type|Boolean, true}, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|VarInt, 1}, Pair{Type|Byte, 118}, Pair{Type|Byte, 96}, Pair{Type|Byte, 1}, Pair{Type|Boolean, true}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$10 (Anonymous), Packet ID: 37}
[12:38:03] [Netty Epoll Server IO #3/WARN]: Actual Error: 
[12:38:03] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 256)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:40)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:48)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:41)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:32)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:171)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viabackwards.api.rewriters.MapColorRewriter.lambda$getRewriteHandler$0(MapColorRewriter.java:41)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:289)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:268)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:38:03] [Netty Epoll Server IO #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[12:38:03] [Server thread/INFO]: Jorge211 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: JsonElement, Data: [Pair{Type|VarInt, 659}, Pair{Type|Byte, 0}, Pair{Type|Boolean, true}, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|VarInt, 1}, Pair{Type|Byte, 118}, Pair{Type|Byte, 96}, Pair{Type|Byte, 1}, Pair{Type|Boolean, true}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$10 (Anonymous), Packet ID: 37}
Actual Error: 
```

### Bug Description

On server 1.17, join mc client 1.16, treasure map on inventory

### Steps to Reproduce

1- Login 1.16 client to mc sv 1.17
2- Put tresaure map on inventory

### Expected Behavior

No kick

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Update to ci builds.
