### ISSUE TITLE
1.12 forge client is kicked when joining 1.16 paper server

### ISSUE THREAD

**Issue by HamsterYDS** [ViaVersion/ViaBackwards#428]
### '/viaversion dump' Output

We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/fb1f00a477fd16f1f63be4533c2c72193a1e7417da81a045d0abc38e4b1a30c3

### Console Error

[13:08:08 WARN]: [ViaVersion] ERROR IN Protocol1_14_4To1_15 IN REMAP OF ENTITY_METADATA (0x44)
[13:08:08 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[13:08:08 WARN]: {Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous)}
[13:08:08 WARN]: Actual Error:
[13:08:08 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[13:08:08 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[13:08:08 WARN]:        at su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:112)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[13:08:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:08:08 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[13:08:08 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[13:08:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[13:08:08 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[13:08:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[13:08:08 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:08:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[13:08:08 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[13:08:08 WARN]: {Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous)}
[13:08:08 WARN]: Actual Error:
[13:08:08 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.entityNames" is null
[13:08:08 WARN]:        at com.viaversion.viabackwards.api.data.BackwardsMappings.mappedEntityName(BackwardsMappings.java:157)
[13:08:08 WARN]:        at com.viaversion.viabackwards.api.entities.storage.EntityData.mobName(EntityData.java:79)
[13:08:08 WARN]:        at com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.handleMetadata(EntityRewriterBase.java:78)
[13:08:08 WARN]:        at com.viaversion.viaversion.rewriter.EntityRewriter$6.lambda$registerMap$0(EntityRewriter.java:353)
[13:08:08 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[13:08:08 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[13:08:08 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[13:08:08 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[13:08:08 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[13:08:08 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[13:08:08 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[13:08:08 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[13:08:08 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[13:08:08 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[13:08:08 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor224.invoke(Unknown Source)
[13:08:08 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:08:08 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[13:08:08 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[13:08:08 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[13:08:08 WARN]:        at su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:112)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[13:08:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:08:08 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[13:08:08 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[13:08:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[13:08:08 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[13:08:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[13:08:08 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:08:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[13:08:08 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[13:08:08 WARN]: {Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous)}
[13:08:08 WARN]: Actual Error:
[13:08:08 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[13:08:08 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[13:08:08 WARN]:        at su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:112)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[13:08:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:08:08 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[13:08:08 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[13:08:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[13:08:08 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[13:08:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[13:08:08 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:08:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[13:08:08 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[13:08:08 WARN]: {Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous)}
[13:08:08 WARN]: Actual Error:
[13:08:08 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.entityNames" is null
[13:08:08 WARN]:        at com.viaversion.viabackwards.api.data.BackwardsMappings.mappedEntityName(BackwardsMappings.java:157)
[13:08:08 WARN]:        at com.viaversion.viabackwards.api.entities.storage.EntityData.mobName(EntityData.java:79)
[13:08:08 WARN]:        at com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.handleMetadata(EntityRewriterBase.java:78)
[13:08:08 WARN]:        at com.viaversion.viaversion.rewriter.EntityRewriter$6.lambda$registerMap$0(EntityRewriter.java:353)
[13:08:08 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[13:08:08 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[13:08:08 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[13:08:08 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[13:08:08 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[13:08:08 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[13:08:08 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[13:08:08 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[13:08:08 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[13:08:08 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[13:08:08 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor224.invoke(Unknown Source)
[13:08:08 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:08:08 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[13:08:08 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[13:08:08 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[13:08:08 WARN]:        at su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:112)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[13:08:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[13:08:08 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:08:08 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
[13:08:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[13:08:08 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[13:08:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[13:08:08 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[13:08:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[13:08:08 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:08:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[13:08:08 INFO]: Yanyu lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous)}
Actual Error:

### Bug Description

player is kicked when joining the server
maybe its cuz i update my viabackwards yesterday but still use the old configs
(mappings1.xx.xto1.xx.x.yml)

### Steps to Reproduce

login a 1.12.2 forge client without any mods
join the 1.16.5 server with viabackwards

### Expected Behavior

player is not kicked but play normally

### Additional Server Info

vallina client can join in the server correctly

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--792%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--792%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Update your custom mappings file
