### ISSUE TITLE
1.18 players sometimes can't join the game when joining 1.19 server

### ISSUE THREAD

**Issue by MeowKing** [ViaVersion/ViaBackwards#477]
### '/viaversion dump' Output

https://dump.viaversion.com/32cfcda2bbdcb48aeeef68dfe710fe29044a2242e1fe37aeb126644514d493a5

### Console Error

[17:28:42 INFO]: TheHumburger465 joined the game
[17:28:42 WARN]: [ViaVersion] ERROR IN Protocol1_18_2To1_19_1 IN REMAP OF PLAYER_INFO (0x37)
[17:28:42 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[17:28:42 WARN]: {Packet Type: PLAYER_INFO, Type: VarInt, Data: [Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|UUID, 00000000-0000-0000-0009-01f952957eef}, Pair{Type|String, Demon_bell227}, Pair{Type|VarInt, 2}, Pair{Type|String, textures}, Pair{Type|String, }, Pair{Type|Boolean, true}, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19_1.packets.EntityPackets1_19$5 (Anonymous), Packet ID: 54}
[17:28:42 WARN]: Actual Error:
[17:28:42 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:28:42 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:28:42 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[17:28:42 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[17:28:42 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[17:28:42 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:463)
[17:28:42 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:437)
[17:28:42 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[17:28:42 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[17:28:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[17:28:42 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
[17:28:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[17:28:42 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:28:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:28:42 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[17:28:42 WARN]: {Packet Type: PLAYER_INFO, Type: VarInt, Data: [Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|UUID, 00000000-0000-0000-0009-01f952957eef}, Pair{Type|String, Demon_bell227}, Pair{Type|VarInt, 2}, Pair{Type|String, textures}, Pair{Type|String, }, Pair{Type|Boolean, true}, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19_1.packets.EntityPackets1_19$5 (Anonymous), Packet ID: 54}
[17:28:42 WARN]: Actual Error:
[17:28:42 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(50) + length(1) exceeds writerIndex(50): PooledUnsafeDirectByteBuf(ridx: 50, widx: 50, cap: 256)
[17:28:42 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[17:28:42 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:70)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181)
[17:28:42 WARN]:        at ViaBackwards-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_18_2to1_19_1.packets.EntityPackets1_19$5.lambda$registerMap$0(EntityPackets1_19.java:228)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[17:28:42 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:28:42 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:28:42 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[17:28:42 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[17:28:42 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[17:28:42 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:463)
[17:28:42 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:437)
[17:28:42 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[17:28:42 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[17:28:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[17:28:42 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
[17:28:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[17:28:42 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:28:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:28:42 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[17:28:42 WARN]: {Packet Type: PLAYER_INFO, Type: VarInt, Data: [Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|UUID, 00000000-0000-0000-0009-01f952957eef}, Pair{Type|String, Demon_bell227}, Pair{Type|VarInt, 2}, Pair{Type|String, textures}, Pair{Type|String, }, Pair{Type|Boolean, true}, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19_1.packets.EntityPackets1_19$5 (Anonymous), Packet ID: 54}
[17:28:42 WARN]: Actual Error:
[17:28:42 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:28:42 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:28:42 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[17:28:42 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[17:28:42 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[17:28:42 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:463)
[17:28:42 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:437)
[17:28:42 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[17:28:42 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[17:28:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[17:28:42 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
[17:28:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[17:28:42 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:28:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:28:42 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[17:28:42 WARN]: {Packet Type: PLAYER_INFO, Type: VarInt, Data: [Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|UUID, 00000000-0000-0000-0009-01f952957eef}, Pair{Type|String, Demon_bell227}, Pair{Type|VarInt, 2}, Pair{Type|String, textures}, Pair{Type|String, }, Pair{Type|Boolean, true}, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19_1.packets.EntityPackets1_19$5 (Anonymous), Packet ID: 54}
[17:28:42 WARN]: Actual Error:
[17:28:42 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(50) + length(1) exceeds writerIndex(50): PooledUnsafeDirectByteBuf(ridx: 50, widx: 50, cap: 256)
[17:28:42 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[17:28:42 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:70)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181)
[17:28:42 WARN]:        at ViaBackwards-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_18_2to1_19_1.packets.EntityPackets1_19$5.lambda$registerMap$0(EntityPackets1_19.java:228)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[17:28:42 WARN]:        at ViaVersion-4.4.0-1.19.1-pre5-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[17:28:42 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:28:42 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:28:42 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[17:28:42 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[17:28:42 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[17:28:42 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[17:28:42 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:463)
[17:28:42 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:437)
[17:28:42 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[17:28:42 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[17:28:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[17:28:42 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
[17:28:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[17:28:42 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:28:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:28:42 INFO]: TheHumburger465[/122.6.135.158:28444] logged in with entity id 727900 at ([Home]4953.5, 91.0, 4720.5)
[17:28:42 INFO]: TheHumburger465 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: PLAYER_INFO, Type: VarInt, Data: [Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|UUID, 00000000-0000-0000-0009-01f952957eef}, Pair{Type|String, Demon_bell227}, Pair{Type|VarInt, 2}, Pair{Type|String, textures}, Pair{Type|String, }, Pair{Type|Boolean, true}, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|Boolean, false}, Pair{Type|VarInt, 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19_1.packets.EntityPackets1_19$5 (Anonymous), Packet ID: 54}
Actual Error:
[17:28:42 INFO]: TheHumburger465 left the game

### Bug Description

Players below 1.19 get kicked once in a while

### Steps to Reproduce

1.Login with a client below 1.19
2.Get kicked with errors

### Expected Behavior

Players should be allowed to join the server with any versions

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1714%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Purpur--1714%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0-1.19.1-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.4.0--1.19.1--pre5--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.0-1.19.1-pre5-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.4.0--1.19.1--pre5--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Please use ViaBackwards 4.3.1 - the dev version does not support 1.19 servers anymore
