### ISSUE TITLE
com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3. packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55

### ISSUE THREAD

**Issue by spookymgmt** [ViaVersion/ViaBackwards#512]

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--53%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Pufferfish--53%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by spookymgmt** [comment]
```
[20:43:12] [Netty Epoll Server IO #0/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[20:43:12] [Netty Epoll Server IO #0/WARN]: Packet Type: PLAYER_INFO, Type: String, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[20:43:12] [Netty Epoll Server IO #0/WARN]: Caused by: java.lang.IndexOutOfBoundsException: index: 66861, length: -396207962 (expected: range(0, 131072))
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:481)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:130)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1270)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:54)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaBackwards-4.5.2-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3.lambda$registerMap$0(EntityPackets1_19_3.java:132)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:60)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:38)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:43:12] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)``` I removed all the plugins in the error, and now it's giving the error by it's self. The issue is clearly via* or protocollib. Right?

**Comment by spookymgmt** [comment]
I removed all the plugins in the error, and now it's giving the error by it's self. The issue is clearly via* or protocollib. Right?

**Comment by spookymgmt** [comment]
All of my gamemodes are experiecing this viaver error BESIDES one.

Here's a list of plugins that my ERROR'd servers have, that my GOOD server doesnt
```
Afkwarner (When essentials sets a player to afk status, this plugin makes it so when you dm an afk player, it returns a msg saying "theyre afk, try later")
Antidrop (Makes it so you have to press q twice to drop items)
Chunkborders (Left click with stick for a wool outline of the chunk)
Claimchat (Allows you to chat to people in your claim)
ClaimSignFixer (Allows you to break chestshop signs in your claim)
CosmicPlaytime (Checks playtime of a player on server)
CraftableCobweb (Allows you to craft cobwebs)
DenyTravel (Blocks mobs from traveling thru nether portals)
DuelAnywhere (Allows you to pvp anywhere with kits)
Exchanger (Allows you to trade x items for y reward)
GPClaimexpiration (Makes griefprevent claim expire after x inactivty)
GriefPrevention claim plugin
GriefPreventionFlags (flags for claim plugin)
GriefPreventionTP (allows you to teleport to your gp claims)
ImageMaps (Allows you to place images on a map in game
InfiniteBlocks (Special item that is the infinite version ie infinite cobble, allows you to place infinite times.)
InvisibleItemFrames (Makes item frames invisible)
Itemblocker (Makes it so you cannot consume items with configured lore)
LibsDisguises (Disguise plugin)
LockettePro (Chest locking plugin)
MarriageMaster (Marry plugin)
NotTooExpensive (Makes anvil never charge more than 30 levels)
Pl3xmap-Griefprevent (Shows claims on squaremap map)
Pl3xmap-Supervanish (Disables vanished players on squaremap map)
PocketGames (Gui minigames)
QuickShop (Chest shops)
Sleep-Most (If 75% of server sleeps same time, it turns to day)
Squaremap (Server map)
Vehicles (Vehicle plugin using armor stands)
Voigenerator (generate world as void)```

**Comment by spookymgmt** [comment]
Don't know if relevant, just putting it here incase.

[15:40:38] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] Error when trying to parse json: �B����J5��BLUEOVERFLOWtextures�ewogICJ0aW1lc3
[15:40:38] [Netty Epoll Server IO #0/WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[15:40:38] [Netty Epoll Server IO #0/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[15:40:38] [Netty Epoll Server IO #0/WARN]: Packet Type: PLAYER_INFO, Type: JsonElement, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55

The above shows a json string? dunno

**Comment by spookymgmt** [comment]
[15:45:52] [Netty Epoll Server IO #5/ERROR]: [ViaVersion] Error when trying to parse json: DI��(�ÏY�Smithsonitetextures�ewogICJ0aW1lc3RhbXAiIDogMTY3Mjg0NTQ2NTMxNiwKICAicHJvZmlsZUlkIiA6ICI3ZTkyMDhkYWY3MDM0NDQ5OGFkNTI4ZWJjMzhmNTlkMiIsCiAgInByb2ZpbGVOYW1lIiA6ICJTbWl0aHNvbml0ZSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS81NDcxZTgzNzU2Yjg5NDU0YmIwOTU3NTY5NjI1NzQ0MmUxYjkzZTNkMWZkOGYyMmI2NmJiNmU4ZDgyNDJjYjQzIgogICAgfQogIH0KfQ==�dA+dFxy0yX+gp5TGLMPbV2kYHbqBI4SbsUhy4q6Trw9pDq0QfF
[15:45:52] [Netty Epoll Server IO #5/WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[15:45:52] [Netty Epoll Server IO #5/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[15:45:52] [Netty Epoll Server IO #5/WARN]: Packet Type: PLAYER_INFO, Type: JsonElement, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:767)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:45:52] [Netty Epoll Server IO #5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by spookymgmt** [comment]
https://github.com/CitizensDev/Citizens2/issues/2974

**Comment by masmc05** [comment]
without viaversion installed on the server, the exception starts to occur on the velocity

**Comment by spookymgmt** [comment]
Still need help.

> without viaversion installed on the server, the exception starts to occur on the velocity

send the error that occurs on velocity

**Comment by masmc05** [comment]
> Still need help.
> 
> > without viaversion installed on the server, the exception starts to occur on the velocity
> 
> send the error that occurs on velocity

we will continue investigation and when we'll find what's the issue, I'll tell you
but here's the screenshot of the error 
![Screenshot_20230108-222912_Gallery](https://user-images.githubusercontent.com/63639746/211217636-12888792-b5cf-4d48-8de7-2f183a2eeb62.png)

**Comment by masmc05** [comment]
update, i made a plugin which logs info about player info packets, and also tries to reserialize them, when this error occurs, the reserialization fails due to malformated chat signing bytes
![Screenshot_20230110-162608_Termux](https://user-images.githubusercontent.com/63639746/211579978-f0bff810-6592-4640-8433-184884ad3cbc.png)

**Comment by masmc05** [comment]
update, made https://github.com/masmc05/PacketHelp
it detects and kicks players with damaged game profiles, before they cause this error

**Comment by kennytv** [comment]
At this point I am almost certain that it's caused by plugins mutating game profiles or their properties, since profiles aren't thread safe (at least before one of the recent 1.21.something versions). They should always be fully replaced instead, else it results in botched packets
