### ISSUE TITLE
ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF ADVANCEMENTS (0x65)

### ISSUE THREAD

**Issue by KLONOA9X6** [ViaVersion/ViaBackwards#516]
### '/viaversion dump' Output

https://dump.viaversion.com/52ea91694c0ec0e61667c88b875cace263a02e47af44e56af0f40cb7dad761f6

### Console Error

```
[01:02:30] [Netty Server IO #0/WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF ADVANCEMENTS (0x65)
[01:02:30] [Netty Server IO #0/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[01:02:30] [Netty Server IO #0/WARN]: Source 0: com.viaversion.viabackwards.api.rewriters.ItemRewriter$1 (Anonymous)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[01:02:30] [Netty Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[01:02:30] [Netty Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:02:30] [Netty Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:02:30] [Netty Server IO #0/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[01:02:30] [Netty Server IO #0/WARN]: Source 0: com.viaversion.viabackwards.api.rewriters.ItemRewriter$1 (Anonymous)
[01:02:30] [Netty Server IO #0/WARN]: Caused by: java.lang.ClassCastException: class com.viaversion.viaversion.libs.opennbt.tag.builtin.CompoundTag cannot be cast to class com.viaversion.viaversion.libs.opennbt.tag.builtin.StringTag (com.viaversion.viaversion.libs.opennbt.tag.builtin.CompoundTag and com.viaversion.viaversion.libs.opennbt.tag.builtin.StringTag are in unnamed module of loader 'ViaVersion-4.5.2-SNAPSHOT.jar' @2c4641d0)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaBackwards-4.5.2-SNAPSHOT.jar//com.viaversion.viabackwards.api.rewriters.ItemRewriter.handleItemToClient(ItemRewriter.java:48)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaBackwards-4.5.2-SNAPSHOT.jar//com.viaversion.viabackwards.api.rewriters.ItemRewriter$1.lambda$registerMap$0(ItemRewriter.java:142)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:381)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[01:02:30] [Netty Server IO #0/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:36)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[01:02:30] [Netty Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[01:02:30] [Netty Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:02:30] [Netty Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:02:30] [Netty Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:02:30] [Server thread/INFO]: CHN_96_STUDIO lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.api.rewriters.ItemRewriter$1 (Anonymous)
```

### Bug Description

Remap advancements failed

### Steps to Reproduce

1.Download the [datapack](https://github.com/KLONOA9X6/Lunatea) to world/datapacks folder.
2.Start server.
3.Try to log in server

### Expected Behavior

Can't join the server.

### Additional Server Info

Using paper-1.19.3-365
Plugins (14): CoreProtect, CustomCrafting, dynmap, Essentials, EssentialsChat, LuckPerms, MultiLogin, ProjectileKnockback, UnsignedMessages, Vault, ViaBackwards, ViaVersion, WolfyUtilities, WorldEdit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--365%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--365%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Possibly an issue with third-party plugin, Please perform a binary search to see what causes it to happen.
