### ISSUE TITLE
The 1.19.2 client will throw a error "net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:menu contains IDs unknown to the receiver!  - minecraft:legacy_smithing" while the player join a 1.19.4 server with viabackward

### ISSUE THREAD

**Issue by disymayufei** [ViaVersion/ViaBackwards#536]
### '/viaversion dump' Output

https://dump.viaversion.com/f6896c1ad721ff4d666bbc8dc1a622dc8af12becdc7dcd6c4ad2bbd590b79e18

### Console Error

[23:58:50] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:menu contains IDs unknown to the receiver!
 - minecraft:legacy_smithing
	at net.minecraft.class_2370.remap(class_2370.java:736) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:314) ~[fabric-registry-sync-v0-0.9.26+c6af733c90-138b79ffabdb92dc.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:125) ~[fabric-registry-sync-v0-0.9.26+c6af733c90-138b79ffabdb92dc.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at net.minecraft.class_1255.redirect$zik000$redirectExecuteTask(class_1255.java:521) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]

### Bug Description

I update my server to 1.19.4, and then try to use 1.19.2 client join the server. The client will stuck a few second and then show the error "net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:menu contains IDs unknown to the receiver! - minecraft:legacy_smithing", and the server shows that I'm timed out.

![image](https://user-images.githubusercontent.com/72013933/226543222-e2e2f8e5-503a-43ce-89e9-d92ea9990535.png)

### Steps to Reproduce

1. Only set up the ViaVersion and ViaBackward (both 4.6.2-SNAPSHOT) into the 1.19.4 fabric server.
2. Write a Mod at will and register a ScreenHandler, and make the mod both suit for Minecraft 1.19.2 and 1.19.4.
3. Both set up this mod into 1.19.4 server and 1.19.2 client, and then restart the server.
4. Use the 1.19.2 client with the ScreenHandler mod join the 1.19.4 server.
5. The bug will occur.

### Expected Behavior

The client won't be kick out of the server although it register a ScreenHandler.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 0.4.9+28--main](https://img.shields.io/badge/Platform-0.4.9+28--main-3498db?style=flat-square) </br>![ViaVersion (4.6.1): 10 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.1)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by disymayufei** [comment]
new dump: https://dump.viaversion.com/4977a7ab06b72f341ccdae5a5c75c33f4198c18c6d8b3668d5ed67d8e365b870

**Comment by Barvalg** [comment]
![Platform: 0.4.9+28--main](https://img.shields.io/badge/Platform-0.4.9+28--main-3498db?style=flat-square) </br>![ViaVersion (4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
