### ISSUE TITLE
Please report this on the Via support Dis cord or open an issue on the relevant GitHub repository

### ISSUE THREAD

**Issue by postyizhan** [ViaVersion/ViaBackwards#544]
### '/viaversion dump' Output

https://dump.viaversion.com/bcd39675deb3 5560e1af96b658d41be6af67535ffd20d35683f8e3eaa0e74dff

### Console Error

```
Put the paste.gg link or text here.
```
[20:11:05 ERROR]: [/127.0.0.1:59604|XYZ_2022] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Dis
cord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.EntityPackets$6 (Anonymous), Source 1: com.viaversion.viaversion.
protocols.protocol1_14to1_13_2.packets.WorldPackets$9 (Anonymous)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[waterfall-1.19-526.jar:git:Waterfall-Boo
tstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall-1.19-526.jar:git:
Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[waterfall-1.19-526.jar:git:W
aterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[waterfall-1.19-526.jar:git:Waterfa
ll-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[waterfall-1.19-526.jar:git:Waterfa
ll-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap
:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall-1.19-526.jar:git:
Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[waterfall-1.19-526.j
ar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[waterfall-1.19-526.jar:git:Waterfa
ll-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[waterfall-1.19-526.jar:git
:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[waterfall-1.19-526.jar:git:Waterfall-Bo
otstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0
.1-SNAPSHOT:3df3a27:526]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNA
PSHOT:3df3a27:526]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-S
NAPSHOT:3df3a27:526]
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:357) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPS
HOT:3df3a27:526]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:228) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:
3df3a27:526]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SN
APSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:g
it:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap
:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:g
it:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-526.jar:git:Waterfa
ll-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:g
it:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-526.jar:git:Waterfa
ll-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:g
it:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.19-526.jar:git:Waterfall
-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall-1.19-526.jar:git:Waterfall-Boo
tstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-526.jar:g
it:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.19-526.jar:git:Wa
terfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-526.jar
:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.19-526.jar:git:Waterfall-B
ootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.19-526.jar:git:Wate
rfall-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19
-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[waterfall-1.19-526.jar:git:Waterfall-Boot
strap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.1
9-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:
3df3a27:526]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-526.jar:git:Waterfa
ll-Bootstrap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-526.jar:git:Waterfall-Bootstrap:1.19-R
0.1-SNAPSHOT:3df3a27:526]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the r
elevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.EntityPackets$6 (Anonymous), Source 1: com.viaversion.viaversion.
protocols.protocol1_14to1_13_2.packets.WorldPackets$9 (Anonymous)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.dimensions" is null
        at com.viaversion.viaversion.protocols.protocol1_19to1_18_2.storage.DimensionRegistryStorage.dimensionKey(DimensionRegistryStorage.j
ava:30) ~[?:?]
        at com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.EntityPackets.writeDimensionKey(EntityPackets.java:312) ~[?:?]
        at com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.EntityPackets.access$400(EntityPackets.java:52) ~[?:?]
        at com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.EntityPackets$6.lambda$register$0(EntityPackets.java:255) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:390) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.constructPacket(PacketWrapperImpl.java:318) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:272) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send(PacketWrapperImpl.java:260) ~[?:?]
        at com.viaversion.viaversion.api.protocol.packet.PacketWrapper.send(PacketWrapper.java:178) ~[?:?]
        at com.viaversion.viaversion.protocols.protocol1_14to1_13_2.packets.WorldPackets$9.lambda$register$2(WorldPackets.java:301) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:390) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:378) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:54) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[waterfall-1.19-526.jar:git:Waterfall-Boot
strap:1.19-R0.1-SNAPSHOT:3df3a27:526]
        ... 48 more

### Bug Description

I installed viaversion and viaBackwards on waterfall
, I have problems when I use /server crossover (from Bing Translate)

### Steps to Reproduce

1.Place the plugin in ./plugins/ folder.
2.Restart the server.
3.use /server test

### Expected Behavior

I'll be kicked out of the game
![Uploading _ZVN0SM3BTI89F8Q)X@JH9S.png…]()

### Additional Server Info

AdvancedBan, Geyser-BungeeCord, LuckPerms, MiniMOTD, ServerUtils, SkinsRestorer, TrChat, ViaBackwards, ViaVe
rsion and floodgate

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by postyizhan** [comment]
> 

https://dump.viaversion.com/bcd39675deb3 5560e1af96b658d41be6af67535ffd20d35683f8e3eaa0e74dff

Sorry, there is an extra space in between

**Comment by postyizhan** [comment]
> ![Error: Invalid or missing dump](https://camo.githubusercontent.com/d52699b4f8c5e7e91cb92ecd59b5aa5ed2f9eb37e741b87aa9334b5e364c0512/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)

https://dump.viaversion.com/bcd39675deb35560e1af96b658d41be6af67535ffd20d35683f8e3eaa0e74dff

Sorry, there is an extra space in between

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by postyizhan** [comment]
> 

When I wrote this issue, I saw the plugin version update of the build site, so I tried it before posting this issue, and I made a new dump

https://dump.viaversion.com/1497bb745158a8e572d11b8883280f5ca8eaeb14f8eb5e838c930e2bdd1a3f21

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A3df3a27%3A526-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by postyizhan** [comment]
> Please attempt to move via* to the backend servers only to see if your problem continues to happen.

Do you mean to put via on spigot/paper servers as well?
I tried installing via on the server I'm going to connect to as well and it really worked
Thank you both very much for your help, although I don't understand what happened

**Comment by Kichura** [comment]
> > Please attempt to move via* to the backend servers only to see if your problem continues to happen.
> 
> Do you mean to put via on spigot/paper servers as well? I tried installing via on the server I'm going to connect to as well and it really worked Thank you both very much for your help, although I don't understand what happened

I am likely assuming a third-party plugin caused via*'s guessing on proxy side to break entirely, but because of this; i will mark this issue as resolved.
