### ISSUE TITLE
Bungeecord+ViaBackwards dont works together longer

### ISSUE THREAD

**Issue by wotnurwasfrage** [ViaVersion/ViaBackwards#576]
### '/viaversion dump' Output

https://dump.viaversion.com/163ecdd0b7b4177e6d1502397f60a3a1b25edcc2a13c8e8aca940685998e74d6

### Console Error

disconnected with: §fEncoderException : com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_19_4to1_20.packets.EntityPackets1_20$1 (Anonymous) @ io.netty.handler.codec.MessageToMessageEncoder:107

 -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_19_4to1_20.packets.EntityPackets1_20$1 (Anonymous)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
	at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:149)
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:231)
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:237)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_19_4to1_20.packets.EntityPackets1_20$1 (Anonymous)
Caused by: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.libs.opennbt.tag.builtin.CompoundTag.get(String)" because the return value of "com.viaversion.viaversion.libs.opennbt.tag.builtin.CompoundTag.get(String)" is null
	at com.viaversion.viabackwards.protocol.protocol1_19_4to1_20.packets.EntityPackets1_20$1.lambda$register$0(EntityPackets1_20.java:79)
	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
	at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:54)
	at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:30)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
	at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:149)
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:231)
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:237)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Bug Description

hi, i upgraded my bungeecordsystem with java17
i used all 3 via-plugins before on it with java11
but now i can only have viaversion+viaRewind on bungeecord, cause viaBackwards creates that issue.
if i have them 3 via plugins on the server its no problem. but, i need them on bungeecord, cause some serverplugins stop working with viarewind inside..

i tried now with the actual dev builds also. viaversion 4.8.0 / viaRewind 2.0.4 / viabackwards 4.8.0)
but then i cant join with 1.19.4 on spigot 1.16.5 server and get just these messages:
disconnected with: §cKicked whilst connecting to hub: §fOutdated client! Please use 1.16.5

<-> InitialHandler - could not decode packet! com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: UUID, Index: 3, Data: [{String: cuute}, {ProfileKey: null}], Source 0: com.viaversion.viaversion.protocols.protocol1_19_1to1_19.Protocol1_19_1To1_19$7 (Anonymous), Packet ID: 0

### Steps to Reproduce

1. java17 from zulu for debian system
2. add all via-plugins on bungeecord (viaVersion 4.7.0 / viaBackwards 4.7.0 /viaRewind 2.0.3)
3. start bungeecord with that java17
4. join with mc version 1.19.4 (or equal the version) and the issue comes
5. remove viaBackwards from bungeecord and restart
6. join again with 1.19.4 and you can join the server

### Expected Behavior

cant join the server while viaBackwards is on Bungeecord,
but i need them on bungeecord, cause some important plugins dont work with viaRewind together (BigDoors dont load the plugin if its on same server where viaRewind also is running. if viaRewind is on bungeecord it all works. maybe buggy on lower versions, but it works)

### Additional Server Info

Bungeecord
Spigot
java17 from zulu

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.1--SNAPSHOT%3A0199cb9%3A1720](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.1--SNAPSHOT%3A0199cb9%3A1720-3498db?style=flat-square) </br>![Proxy is 3 builds behind](https://img.shields.io/badge/Your%20proxy%20is%203%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.0-23w32a-SNAPSHOT): 10 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--23w32a--SNAPSHOT)-10%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.0-23w32a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.8.0--23w32a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by wotnurwasfrage** [comment]
https://dump.viaversion.com/163ecdd0b7b4177e6d1502397f60a3a1b25edcc2a13c8e8aca940685998e74d6

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.1--SNAPSHOT%3A0199cb9%3A1720](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.1--SNAPSHOT%3A0199cb9%3A1720-3498db?style=flat-square) </br>![Proxy is 3 builds behind](https://img.shields.io/badge/Your%20proxy%20is%203%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.0-23w32a-SNAPSHOT): 10 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--23w32a--SNAPSHOT)-10%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(2.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.0-23w32a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.8.0--23w32a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by wotnurwasfrage** [comment]
how the ViaVersion can be 10commits behind the dev version?
i use the dev from Build #869 (10.08.2023, 12:22:09 its to one on the top or i am blind?

**Comment by FormallyMyles** [comment]
There was an issue with our CI which has now been resolved relating to the 10 commits behind message.

Otherwise, you want to try these builds (not the -DEV prefix for now):

ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.7.1-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/build/libs/ViaBackwards-4.7.1-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-2.0.4-SNAPSHOT.jar

You may want to try also without other bungee plugins if it continues to happen or perhaps putting the Via* plugins on just the backend servers. Also, ensure you update Bungee.

**Comment by wotnurwasfrage** [comment]
thank you <3 that looks to work now again 🥉 
btw, how much RAM i should give bungeecord while use the via* plugins? i dont have an issue about that, but, how much would make sense? i gave it 1,5GB

**Comment by FormallyMyles** [comment]
> thank you <3 that looks to work now again 💯 btw, how much RAM i should give bungeecord while use the via* plugins? i dont have an issue about that, but, how much would make sense? i gave it 1,5GB

The current amount should be enough but I'd just monitor and increase if needed

**Comment by wotnurwasfrage** [comment]
hi, i have an additional issue..
```
17:06:42 [WARNING] [KnabberLuki] Cannot correctly update tablist for player KnabberLuki
The client and server versions do not match. Client >= 1.19.3, server < 1.19.3.
Use ViaVersion on the spigot server for the best experience.
```
i dont had this on earlier versions.. is that fixable?

**Comment by FormallyMyles** [comment]
> hi, i have an additional issue..
> 
> ```
> 17:06:42 [WARNING] [KnabberLuki] Cannot correctly update tablist for player KnabberLuki
> The client and server versions do not match. Client >= 1.19.3, server < 1.19.3.
> Use ViaVersion on the spigot server for the best experience.
> ```
> 
> i dont had this on earlier versions.. is that fixable?

I would follow the instructions if you're having that as an issue of moving it to the backend

**Comment by wotnurwasfrage** [comment]
which instructions?
i need them on bungeecord..
it all worked before on older versions... its a new thing..
(btw can i write here again, or should i open a new issue? i was in fact at the point just few second before to post the new issue, but you answered faster than i had finished the new issue^^ cause its closed here, and dont know if you want that here..)

but, you mean maybe that i should test it right? if it work normally on the server than the bungeecord..
i do this now, but, i dont like it, cause i like to make bungeecord some things and dont stress the servers with.. i need cpu+ram for their own usage.. i realy would like if bungeecord can do the via* plugins work, than let the servers do all..

(i written here cause i got the via* plugins from here)

**Comment by wotnurwasfrage** [comment]
so via* plugins stop support bungeecord? or could it be that it work in the future again?.. (future versions)

it makes me sad... cause the backend servers have to do enough...

**Comment by FormallyMyles** [comment]
> so via* plugins stop support bungeecord? or could it be that it work in the future again?.. (future versions)
> 
> it makes me sad... cause the backend servers have to do enough...

The backend support has data from the server so works better, other plugins can't hook into via when it's on the bungee. It's up to you at the end of the day

**Comment by wotnurwasfrage** [comment]
wait, i forgot.. i CANT use via* plugins on the servers... ViaRewind make stop an important bigdoors plugin...
maybe the plugin works a bit buggy but all works.. better than its NOT work.

so i have to life with, to not have the tablist if i am not connect with same serverversion? -.- much thanks -.-
its not up to me.. i have to remove important features from my server if you dont support bungeecord plugins.. it worked all fine before.. just the update for 1.19 makes all difficult -.-

**Comment by wotnurwasfrage** [comment]
so, i have to use them on bungeecord. have no choice..
if i use a 1.16.5 client it works on same spigot version and also to 1.8 spigot version, but not up to 1.19.4
okay.. its a new version issue, not a complete missing feature. 

much thanks to work on 4.7.1 version and to support me.
i still hope there comes anytime a version that supports bungee by higher versions, but, so, i can exist i think.. have no choice :c
