### ISSUE TITLE
The bug is Via backwards is not working in my server and showing this error

### ISSUE THREAD

**Issue by Rustbreaker17** [ViaVersion/ViaBackwards#590]
### '/viaversion dump' Output

https://dump.viaversion.com/d133839b38a1e9807b08abc9d118c3326a05542e06f5fce2f3870f5ed159182e

### Console Error

[10:26:50 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'ViaBackwards-4.7.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:150) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:428) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at com.viaversion.viaversion.api.Via.manager(Via.java:84) ~[PlugManX.jar:?]
        at com.viaversion.viaversion.api.Via.getManager(Via.java:50) ~[PlugManX.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.<init>(BukkitPlugin.java:33) ~[ViaBackwards-4.7.0.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.3.jar:git-Paper-448]

### Bug Description

idk its just not working

### Steps to Reproduce

get on 1.19.3 server and use both viaversion and viabackwards

### Expected Behavior

well viabackwards wont start and would show the stuff

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--448%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--448%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Your JAR is corrupted or you used `/reload confirm` / PlugManX which we do not support.
