### ISSUE TITLE
Error in protocol1_12_2to1_13 BlockItemPackets1_13

### ISSUE THREAD

**Issue by bessel28** [ViaVersion/ViaBackwards#635]
### '/viaversion dump' Output

https://dump.viaversion.com/a0c12192a7b39bc5c1ca2fe26775fddbc28554dd0f7270a198a984f2ab260e28

### Console Error

```
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$9 (Anonymous)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:243) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:327) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:159) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:78) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$9 (Anonymous)
Caused by: java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.Integer (java.lang.Class and java.lang.Integer are in module java.base of loader 'bootstrap')
        at com.viaversion.viaversion.libs.fastutil.ints.Int2ObjectFunction.get(Int2ObjectFunction.java:137) ~[?:?]
        at com.viaversion.viaversion.libs.fastutil.ints.Int2ObjectMap.get(Int2ObjectMap.java:184) ~[?:?]
        at com.viaversion.viaversion.libs.opennbt.conversion.ConverterRegistry.convertToValue(ConverterRegistry.java:111) ~[?:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13.rewriteCanPlaceToClient(BlockItemPackets1_13.java:580) ~[?:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13.handleItemToClient(BlockItemPackets1_13.java:551) ~[?:?]
        at com.viaversion.viaversion.rewriter.ItemRewriter.lambda$itemToClientHandler$7(ItemRewriter.java:459) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:236) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:47) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:29) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        ... 56 more
```

### Bug Description

Logging in with 1.8 causes you to disconnect

### Steps to Reproduce

Log in with 1.8 client

### Expected Behavior

Shouldn't be kicked

### Additional Server Info

Using viaversion and viabackwards on a velocity proxy. Server has no plugins installed.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-1.20.3-pre2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--1.20.3--pre2--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-1.20.3-pre1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--1.20.3--pre1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(3.0.4-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaRewind%20(3.0.4--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by bessel28** [comment]
Also has an `[viaversion]: ERROR IN Protocol1_12_2To1_13 IN REMAP OF ENTITY_EQUIPMENT (0x42)` warning above the error but idk if that's connected

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29-3498db?style=flat-square) </br>![Proxy is 2 builds behind](https://img.shields.io/badge/Your%20proxy%20is%202%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.9.2): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
