### ISSUE TITLE
-1.19.4 can't connect [ViaVersion][ViaBackWard]

### ISSUE THREAD

**Issue by csharpinthecsharp** [ViaVersion/ViaBackwards#640]
### '/viaversion dump' Output

https://dump.viaversion.com/3858c6cf0617e3582a9dbb941ae6fda655c9c4c6c9df9804bd68e408900d9f25

### Console Error

```
[00:19:08 WARN]: [ViaBackwards] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!
[00:19:08 WARN]: [ViaBackwards] You have min/max set to -64/256
[00:19:08 INFO]: [+]wohzz
[00:19:08 INFO]: wohzz[/109.221.243.177:51201] logged in with entity id 309 at ([world]-64.60690098957949, 73.15814676123665, 33.48869238886513)
[00:19:09 ERROR]: [ViaVersion] Error when trying to parse json: "                              "}],"text":""}f^�R�19���;�
[00:19:09 WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[00:19:09 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[00:19:09 WARN]: Packet Type: PLAYER_INFO, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$6109/0x000000080191a128, Packet ID: 55
[00:19:09 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:19:09 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:19:09 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:19:09 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:19:09 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[00:19:09 WARN]:        at staffplusplus-core-1.19.27.jar//be.garagepoort.staffplusplus.craftbukkit.common.AbstractPacketHandler.write(AbstractPacketHandler.java:19)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[00:19:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[00:19:09 WARN]:        at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[00:19:09 WARN]:        at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[00:19:09 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:469)
[00:19:09 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:443)
[00:19:09 WARN]:        at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[00:19:09 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[00:19:09 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[00:19:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[00:19:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[00:19:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:19:09 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:19:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:19:09 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[00:19:09 WARN]: Packet Type: PLAYER_INFO, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$6109/0x000000080191a128, Packet ID: 55
[00:19:09 WARN]: Caused by: com.viaversion.viaversion.libs.gson.JsonSyntaxException: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 34 path $
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.libs.gson.JsonParser.parseReader(JsonParser.java:76)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.libs.gson.JsonParser.parseString(JsonParser.java:51)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:44)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:33)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.type.OptionalType.read(OptionalType.java:38)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:146)
[00:19:09 WARN]:        at ViaBackwards-4.8.1.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3.lambda$registerPackets$0(EntityPackets1_19_3.java:178)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[00:19:09 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:19:09 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:19:09 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:19:09 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:19:09 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[00:19:09 WARN]:        at staffplusplus-core-1.19.27.jar//be.garagepoort.staffplusplus.craftbukkit.common.AbstractPacketHandler.write(AbstractPacketHandler.java:19)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[00:19:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[00:19:09 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[00:19:09 WARN]:        at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[00:19:09 WARN]:        at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[00:19:09 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:469)
[00:19:09 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:443)
[00:19:09 WARN]:        at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[00:19:09 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[00:19:09 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[00:19:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[00:19:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[00:19:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:19:09 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:19:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:19:09 WARN]: Caused by: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 34 path $
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.doPeek(JsonReader.java:551)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.peek(JsonReader.java:433)
[00:19:09 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.libs.gson.JsonParser.parseReader(JsonParser.java:71)
[00:19:09 WARN]:        ... 55 more
[00:19:09 INFO]: wohzz lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: PLAYER_INFO, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$6109/0x000000080191a128, Packet ID: 55
[00:19:09 INFO]: [-]wohzz4
```

### Bug Description

On Join if im not 1.19.4 like the spigot version = KICK + console error.
I have via version and via backward [ last versions ] installed

### Steps to Reproduce

1: Spigot paper 1.19.4
2: ViaVersion last v
3:;ViaBAckward lastV

### Expected Behavior

fazff

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
