### ISSUE TITLE
1.16.5 crash when entering the server

### ISSUE THREAD

**Issue by Kennar** [ViaVersion/ViaBackwards#655]
### '/viaversion dump' Output

https://dump.viaversion.com/99bce37040971015e8b8bd7517cd94fd8590bf409bb080f02994613a6df4daae

### Console Error

```
[11:02:23 WARN]: [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF MAP_DATA (0x27)
[11:02:23 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[11:02:23 WARN]: Packet Type: MAP_DATA, Type: BooleanType, Index: 0, Data: [{VarInt: 30}, {ByteType: 1}, {BooleanType: true}, {BooleanType: false}, {VarInt: 1}, {VarInt: 6}, {ByteType: -128}, {ByteType: -128}, {ByteType: 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$7 (Anonymous), Packet ID: 37
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[11:02:23 WARN]:        at AntiPopup-7.2.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:02:23 WARN]:        at TAB v4.1.2.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:02:23 WARN]:        at AntiPopup-7.2.jar//com.github.kaspiandev.antipopup.nms.v1_20_2.PlayerInjector_v1_20_2$1.write(PlayerInjector_v1_20_2.java:57)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[11:02:23 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[11:02:23 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[11:02:23 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[11:02:23 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[11:02:23 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[11:02:23 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[11:02:23 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[11:02:23 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[11:02:23 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[11:02:23 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[11:02:23 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:02:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[11:02:23 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[11:02:23 WARN]: Packet Type: MAP_DATA, Type: BooleanType, Index: 0, Data: [{VarInt: 30}, {ByteType: 1}, {BooleanType: true}, {BooleanType: false}, {VarInt: 1}, {VarInt: 6}, {ByteType: -128}, {ByteType: -128}, {ByteType: 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$7 (Anonymous), Packet ID: 37
[11:02:23 WARN]: Caused by: java.io.IOException: Unable to read type BooleanType, found OptionalComponentType
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:156)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:187)
[11:02:23 WARN]:        at ViaBackwards-4.9.1.jar//com.viaversion.viabackwards.api.rewriters.MapColorRewriter.lambda$getRewriteHandler$0(MapColorRewriter.java:40)
[11:02:23 WARN]:        at ViaBackwards-4.9.1.jar//com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$7.lambda$register$1(BlockItemPackets1_17.java:401)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[11:02:23 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[11:02:23 WARN]:        at AntiPopup-7.2.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:02:23 WARN]:        at TAB v4.1.2.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:02:23 WARN]:        at AntiPopup-7.2.jar//com.github.kaspiandev.antipopup.nms.v1_20_2.PlayerInjector_v1_20_2$1.write(PlayerInjector_v1_20_2.java:57)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[11:02:23 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[11:02:23 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[11:02:23 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[11:02:23 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[11:02:23 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[11:02:23 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[11:02:23 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[11:02:23 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[11:02:23 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[11:02:23 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[11:02:23 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[11:02:23 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[11:02:23 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:02:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)```


### Bug Description

When a player on version 1.16.5 tries to join the server, they are automatically kicked due to an error.

### Steps to Reproduce

1. Entering the server on version 1.16.5

### Expected Behavior

?


### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2092%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2092%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 12 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 10 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-10%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
> I have tried a build from https://ci.viaversion.com/ and the issue still persists.
Please don't check what you didn't do
