### ISSUE TITLE
Version 1.19.4 cannot connect to Paper Server 1.20.4

### ISSUE THREAD

**Issue by chiucs123** [ViaVersion/ViaBackwards#657]
### '/viaversion dump' Output

https://dump.viaversion.com/9bf3fc4e49e525f359624be821a7d9bd2d24ccb9bdc9b9e0234e7c1ad8833de9

### Console Error

[00:51:42 INFO]: Done (20.677s)! For help, type "help"
[00:51:42 INFO]: Timings Reset
[00:51:42 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[00:51:43 WARN]: [ViaVersion] You are running a newer version of the plugin than is released!
[00:51:50 INFO]: UUID of player admin is *********************************************************************
[00:51:51 WARN]: [ViaVersion] ERROR IN Protocol1_20To1_20_2 IN REMAP OF CONFIGURATION 0x05->0xFFFFFFFF
[00:51:51 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[00:51:51 WARN]: Packet Type: null, Type: CompoundTagType, Index: 3, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$Lambda$8278/0x0000000801be9558, Packet ID: -1
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[00:51:51 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.b(NetworkManager.java:430)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:392)
[00:51:51 WARN]:        at net.minecraft.server.network.ServerCommonPacketListenerImpl.a(ServerCommonPacketListenerImpl.java:242)
[00:51:51 WARN]:        at net.minecraft.server.network.ServerCommonPacketListenerImpl.b(ServerCommonPacketListenerImpl.java:227)
[00:51:51 WARN]:        at net.minecraft.server.network.config.ServerResourcePackConfigurationTask.a(ServerResourcePackConfigurationTask.java:19)
[00:51:51 WARN]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.p(ServerConfigurationPacketListenerImpl.java:158)
[00:51:51 WARN]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.m(ServerConfigurationPacketListenerImpl.java:78)
[00:51:51 WARN]:        at net.minecraft.server.network.LoginListener.a(LoginListener.java:408)
[00:51:51 WARN]:        at net.minecraft.network.protocol.login.ServerboundLoginAcknowledgedPacket.a(ServerboundLoginAcknowledgedPacket.java:18)
[00:51:51 WARN]:        at net.minecraft.network.protocol.login.ServerboundLoginAcknowledgedPacket.a(ServerboundLoginAcknowledgedPacket.java:9)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:312)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:294)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:61)
[00:51:51 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[00:51:51 WARN]:        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:51:51 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.lambda$sendRawPacketToServerServerSide$4(UserConnectionImpl.java:250)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.sendRawPacketToServerServerSide(UserConnectionImpl.java:256)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.sendRawPacketToServer(UserConnectionImpl.java:217)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.lambda$sendToServer0$1(PacketWrapperImpl.java:516)
[00:51:51 WARN]:        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
[00:51:51 WARN]:        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
[00:51:51 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[00:51:51 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[00:51:51 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[00:51:51 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[00:51:51 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:51:51 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:51:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:51:51 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[00:51:51 WARN]: Packet Type: null, Type: CompoundTagType, Index: 3, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$Lambda$8278/0x0000000801be9558, Packet ID: -1
[00:51:51 WARN]: Caused by: java.io.IOException: Unable to read type CompoundTagType, found StringType
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:156)
[00:51:51 WARN]:        at ViaBackwards-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2.lambda$registerPackets$9(Protocol1_20To1_20_2.java:140)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[00:51:51 WARN]:        at ViaBackwards-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2.transform(Protocol1_20To1_20_2.java:168)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[00:51:51 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.b(NetworkManager.java:430)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:392)
[00:51:51 WARN]:        at net.minecraft.server.network.ServerCommonPacketListenerImpl.a(ServerCommonPacketListenerImpl.java:242)
[00:51:51 WARN]:        at net.minecraft.server.network.ServerCommonPacketListenerImpl.b(ServerCommonPacketListenerImpl.java:227)
[00:51:51 WARN]:        at net.minecraft.server.network.config.ServerResourcePackConfigurationTask.a(ServerResourcePackConfigurationTask.java:19)
[00:51:51 WARN]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.p(ServerConfigurationPacketListenerImpl.java:158)
[00:51:51 WARN]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.m(ServerConfigurationPacketListenerImpl.java:78)
[00:51:51 WARN]:        at net.minecraft.server.network.LoginListener.a(LoginListener.java:408)
[00:51:51 WARN]:        at net.minecraft.network.protocol.login.ServerboundLoginAcknowledgedPacket.a(ServerboundLoginAcknowledgedPacket.java:18)
[00:51:51 WARN]:        at net.minecraft.network.protocol.login.ServerboundLoginAcknowledgedPacket.a(ServerboundLoginAcknowledgedPacket.java:9)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:312)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:294)
[00:51:51 WARN]:        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:61)
[00:51:51 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[00:51:51 WARN]:        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[00:51:51 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[00:51:51 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.lambda$sendRawPacketToServerServerSide$4(UserConnectionImpl.java:250)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.sendRawPacketToServerServerSide(UserConnectionImpl.java:256)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.sendRawPacketToServer(UserConnectionImpl.java:217)
[00:51:51 WARN]:        at ViaVersion-4.10.0-23w51b-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.lambda$sendToServer0$1(PacketWrapperImpl.java:516)
[00:51:51 WARN]:        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
[00:51:51 WARN]:        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
[00:51:51 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[00:51:51 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[00:51:51 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[00:51:51 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[00:51:51 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:51:51 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:51:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:51:51 INFO]: com.mojang.authlib.GameProfile@52f28507[id=*********************************************************************,name=admin,properties={}] lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: CompoundTagType, Index: 3, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2$$Lambda$8278/0x0000000801be9558, Packet ID: -1
>

### Bug Description

With the following setup, the client cannot connect to the world with the screenshot error message, using different versions and applying VIA* on either velocity/paper side yields the same result.

Paper version git-Paper-330 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: de04cbc)
Velocity 3.3.0-SNAPSHOT (git-21ae82e7-b306).
ViaVersion-4.10.0-23w51b-SNAPSHOT
ViaBackwards-4.10.0-23w51b-SNAPSHOT

![image](https://github.com/ViaVersion/ViaBackwards/assets/39881664/5378ed3f-0f0b-4ec1-b133-e437bc99c149)

### Steps to Reproduce

1. Login with a 1.19.4 client.
2. Enter multiplayer
3. Select the server that goes to the Paper server via Velocity as a proxy.
4. An error message appears after "Joining World" message.

### Expected Behavior

The world loads successfully on all test versions.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--330%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--330%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.10.0--23w51b--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.10.0--23w51b--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by chiucs123** [comment]
I'm quite sure that the above versions are the latest available on the website provided.

![image](https://github.com/ViaVersion/ViaBackwards/assets/39881664/24357bec-2adb-4d72-ad02-31d353434903)
![image](https://github.com/ViaVersion/ViaBackwards/assets/39881664/34afb50f-812f-4695-8370-546368b196b5)
![image](https://github.com/ViaVersion/ViaBackwards/assets/39881664/d8201088-a849-49e5-b834-5f97d1118592)
![image](https://github.com/ViaVersion/ViaBackwards/assets/39881664/97ca3c23-e440-46ad-8748-1dfa18abd192)

**Comment by chiucs123** [comment]
https://dump.viaversion.com/9bf3fc4e49e525f359624be821a7d9bd2d24ccb9bdc9b9e0234e7c1ad8833de9

**Comment by Barvalg** [comment]
![Platform: git--Paper--330%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--330%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.10.0--23w51b--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.10.0--23w51b--SNAPSHOT)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by chiucs123** [comment]
https://dump.viaversion.com/a048e40d5ce1d005b617c4df736f09f08f03af834c19c36adc568651a199f22c

**Comment by Barvalg** [comment]
![Platform: git--Paper--330%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--330%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Either caused by bad world or the unstable paper build you have. *(latter of which is not recommended for use as it can break plugins)*
