### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by csharpinthecsharp** [ViaVersion/ViaBackwards#662]
### '/viaversion dump' Output

https://dump.viaversion.com/5a63d70b18e97559f18d25a1116c43bbb95091e82f5a38b5455811057bb4ea76

### Console Error

 logged in with entity id 19 at ([world]2.5, -60.0, 6.5)
[23:09:24 ERROR]: [ViaVersion] Error when trying to parse json: "                              "}],"text":""}f^�R�19���;�
[23:09:24 WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[23:09:24 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[23:09:24 WARN]: Packet Type: PLAYER_INFO, Type: OptionalComponentType, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda/0x000001515de42ec0, Packet ID: 55
[23:09:24 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:09:24 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:09:24 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:09:24 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[23:09:24 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[23:09:24 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[23:09:24 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[23:09:24 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:469)
[23:09:24 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:443)
[23:09:24 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[23:09:24 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[23:09:24 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[23:09:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[23:09:24 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[23:09:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:09:24 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:09:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:09:24 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[23:09:24 WARN]: Packet Type: PLAYER_INFO, Type: OptionalComponentType, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda/0x000001515de42ec0, Packet ID: 55
[23:09:24 WARN]: Caused by: com.viaversion.viaversion.libs.gson.JsonSyntaxException: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 34 path $
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.libs.gson.JsonParser.parseReader(JsonParser.java:76)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.libs.gson.JsonParser.parseString(JsonParser.java:51)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:44)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:33)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.api.type.OptionalType.read(OptionalType.java:38)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:142)
[23:09:24 WARN]:        at ViaBackwards-4.9.1 (3).jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3.lambda$registerPackets$0(EntityPackets1_19_3.java:191)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[23:09:24 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:09:24 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:09:24 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:09:24 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[23:09:24 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[23:09:24 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[23:09:24 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[23:09:24 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[23:09:24 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:469)
[23:09:24 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:443)
[23:09:24 WARN]:        at ProtocolLib (3).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[23:09:24 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[23:09:24 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[23:09:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[23:09:24 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[23:09:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:09:24 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:09:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[23:09:24 WARN]: Caused by: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 34 path $
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.doPeek(JsonReader.java:551)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.peek(JsonReader.java:433)
[23:09:24 WARN]:        at ViaVersion-4.9.2 (3).jar//com.viaversion.viaversion.libs.gson.JsonParser.parseReader(JsonParser.java:71)
[23:09:24 WARN]:        ... 49 more
[23:09:24 INFO]: Wohzyy lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: PLAYER_INFO, Type: OptionalComponentType, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda/0x000001515de42ec0, Packet ID: 55

### Bug Description

Connection = Kicked

### Steps to Reproduce

Install Via Version + Backward , Paper 1.19.4

### Expected Behavior

Connect

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 30 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-30%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 17 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
