### ISSUE TITLE
UPDATE_SCORE (PACKET ID: 86)

### ISSUE THREAD

**Issue by GlobDark** [ViaVersion/ViaBackwards#683]
### '/viaversion dump' Output

https://dump.viaversion.com/322c02461e1644539d26163d50527aa818dde31e2467a79e38da17839dd97e74

### Console Error

```
[06:05:10 WARN]: [ViaVersion] ERROR IN Protocol1_17_1To1_18 IN REMAP OF UPDATE_SCORE (0x56)
[06:05:10 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[06:05:10 WARN]: Packet Type: UPDATE_SCORE, Type: VarInt, Index: 2, Data: [{StringType: §7}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86
[06:05:10 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:05:10 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:05:10 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[06:05:10 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[06:05:10 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[06:05:10 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[06:05:10 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[06:05:10 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[06:05:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[06:05:10 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[06:05:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[06:05:10 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:05:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[06:05:10 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[06:05:10 WARN]: Packet Type: UPDATE_SCORE, Type: VarInt, Index: 2, Data: [{StringType: §7}], Source 0: com.viaversion.viabackwards.protocol.protocol1_17_1to1_18.Protocol1_17_1To1_18$5 (Anonymous), Packet ID: 86
[06:05:10 WARN]: Caused by: java.io.IOException: Unable to read type VarInt, found ByteType
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:156)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.lambda$map$0(PacketHandlers.java:54)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[06:05:10 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[06:05:10 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:05:10 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:05:10 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[06:05:10 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[06:05:10 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[06:05:10 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[06:05:10 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[06:05:10 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[06:05:10 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[06:05:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[06:05:10 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[06:05:10 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[06:05:10 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:05:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Bug Description

When I enter the server after 5 seconds it expels me, throwing an error corresponding to **io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException:** and thus repeating the cycle every time I enter the server. The server is 1.20.4 and I am trying to login with 1.8.8.

### Steps to Reproduce

Logging in version 1.8.8 with the server being 1.20.4

### Expected Behavior

That the user remains within the server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--423%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--423%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 50 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-50%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 20 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 31 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-31%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
