### ISSUE TITLE
Cannot connect 1.19.4 server with velocity by 1.19.2 client 

### ISSUE THREAD

**Issue by EricYang801** [ViaVersion/ViaBackwards#685]
### '/viaversion dump' Output

https://dump.viaversion.com/bec690d2bab4a7fee1c81c88db499a9c452c605eab31d855eb457a22b091d249

### Console Error

```
disconnected while connecting to survival: Unable to verify player details
[21:58:54 ERROR]: [connected player] Player_name (/ip): unable to connect to server creative
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:7212
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-358.jar:3.3.0-SNAPSHOT (git-ef861819-b358)]
        at java.base/java.lang.Thread.run(Thread.java:1589) [?:?]
```

### Bug Description

I use 1.19.2 client 
And  velocity server has installed viaversion and viabackwards 
also  viafabric has beed install in my fabric server 1.19.4 
but if i remove viafabric
it still happened

### Steps to Reproduce

1. open 1.19.2 client
2. connect 1.19.4 server 
3. The error is displayed

### Expected Behavior

Unable to verify player details

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--ef861819--b358%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--ef861819--b358%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
```Via plugins are only running on EITHER the backend servers (e.g. Paper) OR the proxy (e.g. BungeeCord), not on both.```
Remove Via* plugins from Velocity

**Comment by EricYang801** [comment]
It still happened

**Comment by HowardZHY** [comment]
> It still happened

If you're sure your Velocity is configured with correct address&port, run /viaversion dump on the fabric server
