### ISSUE TITLE
ERROR IN Protocol1_20_2To1_20_3 IN REMAP OF SET_SLOT (0x15)

### ISSUE THREAD

**Issue by MentasChanneL** [ViaVersion/ViaBackwards#722]
### '/viaversion dump' Output

https://dump.viaversion.com/f35b1d90eb641533e7410ab0f1b9e774cbfdcbbc15f26652693d4480ad354f45

### Console Error

```
[18:14:00 WARN]: [ViaVersion] ERROR IN Protocol1_20_2To1_20_3 IN REMAP OF SET_SLOT (0x15)

[18:14:00 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:14:00 WARN]: Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$5 (Anonymous)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:14:00 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:14:00 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:14:00 WARN]: at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[18:14:00 WARN]: at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[18:14:00 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:14:00 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:14:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:14:00 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[18:14:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:14:00 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:14:00 WARN]: at java.base/java.lang.Thread.run(Thread.java:840)
[18:14:00 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:14:00 WARN]: Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$5 (Anonymous)
[18:14:00 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[18:14:00 WARN]: at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[18:14:00 WARN]: at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[18:14:00 WARN]: at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[18:14:00 WARN]: at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[18:14:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[18:14:00 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[18:14:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[18:14:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[18:14:00 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.processText(ComponentRewriter.java:172)
[18:14:00 WARN]: at ViaBackwards-4.9.2.jar//com.viaversion.viabackwards.api.rewriters.ItemRewriter.handleItemToClient(ItemRewriter.java:55)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.rewriter.ItemRewriter.lambda$itemToClientHandler$7(ItemRewriter.java:450)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:14:00 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:14:00 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:14:00 WARN]: at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[18:14:00 WARN]: at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[18:14:00 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:14:00 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:14:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:14:00 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[18:14:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:14:00 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:14:00 WARN]: at java.base/java.lang.Thread.run(Thread.java:840)
[18:14:00 WARN]: [ViaVersion] ERROR IN Protocol1_20_2To1_20_3 IN REMAP OF SET_SLOT (0x15)
[18:14:00 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:14:00 WARN]: Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$5 (Anonymous)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:14:00 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:14:00 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:14:00 WARN]: at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[18:14:00 WARN]: at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[18:14:00 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:14:00 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:14:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:14:00 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[18:14:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:14:00 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:14:00 WARN]: at java.base/java.lang.Thread.run(Thread.java:840)
[18:14:00 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:14:00 WARN]: Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$5 (Anonymous)
[18:14:00 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[18:14:00 WARN]: at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[18:14:00 WARN]: at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[18:14:00 WARN]: at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[18:14:00 WARN]: at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[18:14:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[18:14:00 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[18:14:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[18:14:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[18:14:00 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.processText(ComponentRewriter.java:172)
[18:14:00 WARN]: at ViaBackwards-4.9.2.jar//com.viaversion.viabackwards.api.rewriters.ItemRewriter.handleItemToClient(ItemRewriter.java:55)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.rewriter.ItemRewriter.lambda$itemToClientHandler$7(ItemRewriter.java:450)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[18:14:00 WARN]: at ViaVersion-4.9.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:00 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:14:00 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:14:00 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:14:00 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:14:00 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:14:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:14:00 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[18:14:00 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:14:00 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:14:00 WARN]: at java.base/java.lang.Thread.run(Thread.java:840)
```

### Bug Description

idk why this happened, maybe due to an inventory change

### Steps to Reproduce

When items appeared in the inventory in the 3rd hotbar slot (1-9) and in the chest slot.
Server on 1.20.4; client with 1.20.2

### Expected Behavior

The player should not be kicked because of this

### Additional Server Info

only my plugin on Bukkit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--478%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--478%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.3)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.2): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>broken_jar</details>

**Comment by MentasChanneL** [comment]
https://dump.viaversion.com/91676706fd1d311f50c0bbd6159ac3c09c912d21a2c73e84a59fde13912a9164

**Comment by Barvalg** [comment]
![Platform: git--Paper--478%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--478%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by MentasChanneL** [comment]
https://dump.viaversion.com/91676706fd1d311f50c0bbd6159ac3c09c912d21a2c73e84a59fde13912a9164

**Comment by Barvalg** [comment]
![Platform: git--Paper--478%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--478%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2): 6 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by kennytv** [comment]
The error was either from having a broken jar file or from changing the jar while the server was still running
