### ISSUE TITLE
major bug

### ISSUE THREAD

**Issue by huncutkingus22** [ViaVersion/ViaBackwards#873]
### '/viaversion dump' Output

https://dump.viaversion.com/307abf04208f3054dcd793c266177cabb1e5b2bc286ae88b98bcfb73c3d35c27

### Console Error

[18:31:55] [Netty Epoll Server IO #2/WARN]: [ViaVersion] ERROR IN Protocol1_20_5To1_20_3 IN REMAP OF SET_EQUIPMENT (0x5B)
[18:31:55] [Netty Epoll Server IO #0/WARN]: [ViaVersion] ERROR IN Protocol1_20_5To1_20_3 IN REMAP OF SET_EQUIPMENT (0x5B)
[18:31:55] [Netty Epoll Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_20_5To1_20_3 IN REMAP OF SET_EQUIPMENT (0x5B)
[18:31:55] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:31:55] [Netty Epoll Server IO #2/WARN]: Packet Type: SET_EQUIPMENT, Type: ByteType, Index: 2, Data: [{VarInt: 1670}], Source 0: com.viaversion.viabackwards.protocol.v1_20_5to1_20_3.rewriter.EntityPacketRewriter1_20_5$$Lambda/0x00007fd44d23aa48, Packet ID: 89
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.Connection$2.write(Connection.java:750)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at Azurite-6.0.1.jar//me.keano.azurite.modules.versions.type.VersionLatest$1.write(VersionLatest.java:295)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.Connection.doSendPacket(Connection.java:505)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:490)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:31:55] [Netty Epoll Server IO #2/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:31:55] [Netty Epoll Server IO #2/WARN]: Packet Type: SET_EQUIPMENT, Type: ByteType, Index: 2, Data: [{VarInt: 1670}], Source 0: com.viaversion.viabackwards.protocol.v1_20_5to1_20_3.rewriter.EntityPacketRewriter1_20_5$$Lambda/0x00007fd44d23aa48, Packet ID: 89
[18:31:55] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(1) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 256)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.type.types.ByteType.read(ByteType.java:45)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.type.types.ByteType.read(ByteType.java:29)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaBackwards-5.0.3.jar//com.viaversion.viabackwards.protocol.v1_20_5to1_20_3.rewriter.EntityPacketRewriter1_20_5.lambda$registerPackets$0(EntityPacketRewriter1_20_5.java:78)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-5.0.3.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.Connection$2.write(Connection.java:750)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at Azurite-6.0.1.jar//me.keano.azurite.modules.versions.type.VersionLatest$1.write(VersionLatest.java:295)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.Connection.doSendPacket(Connection.java:505)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:490)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:31:55] [Netty Epoll Server IO #2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:31:55] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:31:55] [Netty Epoll Server IO #1/WARN]: Packet Type: SET_EQUIPMENT, Type: ByteType, Index: 2, Data: [{VarInt: 1670}], Source 0: com.viaversion.viabackwards.protocol.v1_20_5to1_20_3.rewriter.EntityPacketRewriter1_20_5$$Lambda/0x00007fd44d23aa48, Packet ID: 89
[18:31:55] [Netty Epoll Server IO #2/WARN]: [ViaVersion] ERROR IN Protocol1_20_5To1_20_3 IN REMAP OF SET_EQUIPMENT (0x5B)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.Connection$2.write(Connection.java:750)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at Azurite-6.0.1.jar//me.keano.azurite.modules.versions.type.VersionLatest$1.write(VersionLatest.java:295)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.Connection.doSendPacket(Connection.java:505)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:490)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:31:55] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Bug Description

Idk how or when this happend but 10-15 player randomly got kicked from the server when the console started spanning this

### Steps to Reproduce

idk how sadly

### Expected Behavior

idk how sadly

### Additional Server Info

we are using velocity and the server spigot is 1.20.6 with the latest viaversion and viarewind for 1.18.2 players

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.20.6--DEV--fc2a54b%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-1.20.6--DEV--fc2a54b%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (5.0.3): 13 commits behind master](https://img.shields.io/badge/ViaVersion%20(5.0.3)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(5.0.3): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
