### ISSUE TITLE
[1.20.5->1.20.3] ERROR IN Protocol1_20_5To1_20_3 IN REMAP OF DISGUISED_CHAT (0x1E)

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaBackwards#896]
### '/viaversion dump' Output

https://dump.viaversion.com/35e95d46e443b230ca87eae93659905164b3628dbf44d580e2a17e3555f1098b

### Console Error

```
[02:17:47 WARN]: [ViaVersion] ERROR IN Protocol1_20_5To1_20_3 IN REMAP OF DISGUISED_CHAT (0x1E)
[02:17:47 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[02:17:47 WARN]: Source 0: com.viaversion.viaversion.rewriter.ComponentRewriter$$Lambda/0x00000247bff3c7f0
[02:17:47 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[02:17:47 WARN]:        at net.minecraft.network.Connection$2.write(Connection.java:762)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[02:17:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[02:17:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[02:17:47 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
[02:17:47 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
[02:17:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49)
[02:17:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[02:17:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[02:17:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[02:17:47 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[02:17:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[02:17:47 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:17:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[02:17:47 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[02:17:47 WARN]: Source 0: com.viaversion.viaversion.rewriter.ComponentRewriter$$Lambda/0x00000247bff3c7f0
[02:17:47 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.util.SerializerVersion.toComponent(String)" because "input" is null
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.processJsonString(ComponentRewriter.java:419)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.handleWrittenBookContents(ComponentRewriter.java:404)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.handleHoverEvent(ComponentRewriter.java:363)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.processCompoundTag(ComponentRewriter.java:326)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.processTag(ComponentRewriter.java:298)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.processListTag(ComponentRewriter.java:304)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.processCompoundTag(ComponentRewriter.java:321)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.processTag(ComponentRewriter.java:298)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ComponentRewriter.passthroughAndProcess(ComponentRewriter.java:204)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:347)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:323)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[02:17:47 WARN]:        at ViaVersion-5.0.4-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[02:17:47 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[02:17:47 WARN]:        at net.minecraft.network.Connection$2.write(Connection.java:762)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:17:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[02:17:47 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[02:17:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[02:17:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[02:17:47 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
[02:17:47 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
[02:17:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49)
[02:17:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[02:17:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[02:17:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[02:17:47 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[02:17:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[02:17:47 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:17:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[02:17:47 INFO]: Mad_Daniel lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.rewriter.ComponentRewriter$$Lambda/0x00000247bff3c7f0
[02:17:47 INFO]: Mad_Daniel left the game
```

### Bug Description

https://github.com/ViaVersion/ViaVersion/commit/1a9cda05798294b5bfc4589420e53eae75998fab
I'm getting errors since this commit.

### Steps to Reproduce

Share your written books using InteractiveChat plugin. (HoverEvent)

### Expected Behavior

https://ci.viaversion.com/job/ViaVersion/974/ : This version has no bugs.

https://ci.viaversion.com/job/ViaVersion/975/ : This version has book related bug!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.1--120--57c75a4%20%28MC%3A%201.21.1%29](https://img.shields.io/badge/Platform-1.21.1--120--57c75a4%20%28MC%3A%201.21.1%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
