### ISSUE TITLE
[1.21.2->1.21] Smithing Table causes disconnection

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaBackwards#909]
### '/viaversion dump' Output

https://dump.viaversion.com/de2c3c497dbac77f91832f4f01d8be71519667cb525429439900a8d9285ff712

### Console Error

![image](https://github.com/user-attachments/assets/906b295c-42f5-4edd-8748-fbb1c8d5a342)
```
---- Minecraft Network Protocol Error Report ----
// Maybe a shark bit some cable

Time: 2024-11-05 23:23:03
Description: Packet handling error

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at cpu.a(SourceFile:606)
	at fzg.a(SourceFile:1313)
	at acq.a(SourceFile:42)
	at acq.a(SourceFile:9)
	at zj.a(SourceFile:27)
	at bph.d(SourceFile:162)
	at bpl.d(SourceFile:23)
	at bph.B(SourceFile:136)
	at bph.bB(SourceFile:121)
	at fgo.c(SourceFile:1240)
	at fgo.f(SourceFile:882)
	at net.minecraft.client.main.Main.main(SourceFile:256)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at cpu.a(SourceFile:606)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:container_set_data
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at zj.a(SourceFile:56)
	at fzc.a(SourceFile:136)
	at fzc.a(SourceFile:113)
	at zj.a(SourceFile:32)
	at bph.d(SourceFile:162)
	at bpl.d(SourceFile:23)
	at bph.B(SourceFile:136)
	at bph.bB(SourceFile:121)
	at fgo.c(SourceFile:1240)
	at fgo.f(SourceFile:882)
	at net.minecraft.client.main.Main.main(SourceFile:256)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: Paper
```

### Bug Description

When I open the Smithing Table, I get a network protocol error.

### Steps to Reproduce

1. Open 1.21.3 server
2. Connect to 1.21.1 client.
3. Open the Smithing Table.

### Expected Behavior

no disconnection.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21.3--13--42a1901%20%28MC%3A%201.21.3%29](https://img.shields.io/badge/Platform-1.21.3--13--42a1901%20%28MC%3A%201.21.3%29-3498db?style=flat-square) </br>![ViaVersion (5.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.1.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
